// +build !

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"./pkg/apis/k8s/v1alpha1.Grackle":       schema_pkg_apis_k8s_v1alpha1_Grackle(ref),
		"./pkg/apis/k8s/v1alpha1.GrackleSpec":   schema_pkg_apis_k8s_v1alpha1_GrackleSpec(ref),
		"./pkg/apis/k8s/v1alpha1.GrackleStatus": schema_pkg_apis_k8s_v1alpha1_GrackleStatus(ref),
	}
}

func schema_pkg_apis_k8s_v1alpha1_Grackle(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Grackle is the Schema for the grackles API.",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/k8s/v1alpha1.GrackleSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/k8s/v1alpha1.GrackleStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"./pkg/apis/k8s/v1alpha1.GrackleSpec", "./pkg/apis/k8s/v1alpha1.GrackleStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_k8s_v1alpha1_GrackleSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "GrackleSpec defines the desired state of Grackle",
				Properties: map[string]spec.Schema{
					"datastore": {
						SchemaProps: spec.SchemaProps{
							Description: "Datastore is the specification for the storage of Tweets.",
							Ref:         ref("./pkg/apis/k8s/v1alpha1.DatastoreSpec"),
						},
					},
					"ingest": {
						SchemaProps: spec.SchemaProps{
							Description: "Ingest is the specification for the ingest of Tweets.",
							Ref:         ref("./pkg/apis/k8s/v1alpha1.IngestSpec"),
						},
					},
					"web": {
						SchemaProps: spec.SchemaProps{
							Description: "Web is the specification for the Web UI.",
							Ref:         ref("./pkg/apis/k8s/v1alpha1.WebSpec"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"./pkg/apis/k8s/v1alpha1.DatastoreSpec", "./pkg/apis/k8s/v1alpha1.IngestSpec", "./pkg/apis/k8s/v1alpha1.WebSpec"},
	}
}

func schema_pkg_apis_k8s_v1alpha1_GrackleStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "GrackleStatus defines the observed state of Grackle",
				Properties: map[string]spec.Schema{
					"phase": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
				},
			},
		},
		Dependencies: []string{},
	}
}
